server:
  port: 8089

spring:
  profile: main
  profiles:
    active: main
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
#    password: password
    password: postgres
    schema:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        default_schema: sampleschema
  rabbitmq:
    addresses: localhost:5672
rabbit:
  queueName: message_queue
  exchangeName: message_exchange
  routingKey: routing_key

service:
  url: http://localhost:8089/api/details/getDetailsById/