server.port=8089
spring.datasource.url= jdbc:postgresql://localhost:5432/postgres
spring.datasource.username= postgres
spring.datasource.password = password
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update
spring.profiles = local
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQL81Dialect
spring.jpa.properties.hibernate.default_schema: sampleschema